apiVersion: apps/v1
kind: Deployment
metadata:
  name: collectors-card-app-dev
  namespace: dev-sample
  labels:
    app: collectors-card-app
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collectors-card-app
      environment: dev
  template:
    metadata:
      labels:
        app: collectors-card-app
        environment: dev
    spec:
      containers:
        - name: collectors-card-app
          image: 782496497250.dkr.ecr.us-east-1.amazonaws.com/collectors-card/app:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: "256Mi"
              cpu: "128m"
            limits:
              memory: "512Mi"
              cpu: "256m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
