apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: default
type: Opaque
stringData:
  url: "postgresql://cardinal:cardinal123@postgres-service:5432/cardinal"
  host: "postgres-service"
  port: "5432"
  database: "cardinal"
  username: "cardinal"
  password: "cardinal123"
