apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: default
type: Opaque
stringData:
  bucket-name: "cardinal-content-bucket"
  access-key-id: "your-aws-access-key-id"
  secret-access-key: "your-aws-secret-access-key"
