apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
  namespace: default
type: Opaque
stringData:
  secret-key: "sk_test_your_stripe_secret_key"
  publishable-key: "pk_test_your_stripe_publishable_key"
  webhook-secret: "whsec_your_webhook_secret"
