version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - cd backend
      - npm ci

  pre_build:
    commands:
      - echo Running linting and type checks...
      - npm run lint:check
      - npm run format:check
      - npm run type-check

  build:
    commands:
      - echo Building backend...
      - npm run build:api
      - npm run build:lambdas

  post_build:
    commands:
      - echo Build completed on `date`
      # Optional: Add packaging/deploy commands if using Lambda or ECS
      # - npm run deploy

artifacts:
  base-directory: backend/dist
  files:
    - '**/*'
