version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: cc-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: cc_user
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cc-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: cc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cc-network

  # API
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: cc-api
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://cc_user:${DATABASE_PASSWORD}@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - cc-network

volumes:
  postgres_data:
  redis_data:

networks:
  cc-network:
    driver: bridge
