AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for Lambda build artifacts

Parameters:
  ProjectName:
    Type: String
    Default: collectors-card
    Description: Project name used for naming resources

Resources:
  LambdaArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-lambdas
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  LambdaArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LambdaArtifactsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowLambdaServiceToReadObjects
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: !Sub ${LambdaArtifactsBucket.Arn}/*
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt LambdaArtifactsBucket.Arn
              - !Sub ${LambdaArtifactsBucket.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: false

Outputs:
  BucketName:
    Description: Lambda artifacts S3 bucket name
    Value: !Ref LambdaArtifactsBucket
    Export:
      Name: !Sub ${ProjectName}:LambdaArtifactsBucket
  BucketArn:
    Description: Lambda artifacts S3 bucket ARN
    Value: !GetAtt LambdaArtifactsBucket.Arn
    Export:
      Name: !Sub ${ProjectName}:LambdaArtifactsBucketArn
