AWSTemplateFormatVersion: '2010-09-09'
Description: SES email identity setup for magic link authentication

Parameters:
  ProjectName:
    Type: String
    Default: collectors-card
    Description: Project name used for naming resources
  
  SenderEmailAddress:
    Type: String
    Description: Email address to verify and use as sender (e.g., noreply@example.com or your.email@gmail.com)
    AllowedPattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
    ConstraintDescription: Must be a valid email address
  
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

Resources:
  # Email Identity - verifies the sender email
  SESEmailIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref SenderEmailAddress
      DkimSigningAttributes:
        NextSigningKeyLength: RSA_2048_BIT
      FeedbackAttributes:
        EmailForwardingEnabled: false
      MailFromAttributes:
        BehaviorOnMxFailure: USE_DEFAULT_VALUE
      ConfigurationSetAttributes:
        ConfigurationSetName: !Ref SESConfigurationSet

  SESConfigurationSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: !Sub ${ProjectName}-${Environment}-config-set
      SendingOptions:
        SendingEnabled: true
      ReputationOptions:
        ReputationMetricsEnabled: true
      SuppressionOptions:
        SuppressedReasons:
          - BOUNCE
          - COMPLAINT

  SESEventDestination:
    Type: AWS::SES::ConfigurationSetEventDestination
    Properties:
      ConfigurationSetName: !Ref SESConfigurationSet
      EventDestination:
        Name: !Sub ${ProjectName}-${Environment}-events
        Enabled: true
        MatchingEventTypes:
          - send
          - reject
          - bounce
          - complaint
          - delivery
          - open
          - click
        CloudWatchDestination:
          DimensionConfigurations:
            - DimensionName: ses:configuration-set
              DimensionValueSource: MESSAGE_TAG
              DefaultDimensionValue: !Ref SESConfigurationSet
            - DimensionName: ses:caller-identity
              DimensionValueSource: MESSAGE_TAG
              DefaultDimensionValue: !Sub ${ProjectName}-${Environment}

  SESNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${ProjectName}-${Environment}-ses-notifications
      DisplayName: SES Email Notifications
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  SESNotificationTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref SESNotificationTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action:
              - SNS:Publish
            Resource: !Ref SESNotificationTopic
            Condition:
              StringEquals:
                AWS:SourceAccount: !Ref AWS::AccountId

Outputs:
  SenderEmailAddress:
    Description: Verified sender email address
    Value: !Ref SenderEmailAddress
    Export:
      Name: !Sub ${ProjectName}:${Environment}:SESFromEmail
  
  ConfigurationSetName:
    Description: SES Configuration Set name
    Value: !Ref SESConfigurationSet
    Export:
      Name: !Sub ${ProjectName}:${Environment}:SESConfigSet
  
  NotificationTopicArn:
    Description: SNS Topic ARN for SES notifications
    Value: !Ref SESNotificationTopic
    Export:
      Name: !Sub ${ProjectName}:${Environment}:SESNotificationTopic
  
  VerificationInstructions:
    Description: Email verification status
    Value: !Sub |
      Email identity created for ${SenderEmailAddress}.
      
      IMPORTANT: You must verify this email address before you can send emails.
      
      AWS will send a verification email to ${SenderEmailAddress}.
      Click the verification link in that email to complete the setup.
      
      Check verification status with:
      aws ses get-email-identity --email-identity ${SenderEmailAddress} --region ${AWS::Region} --profile <your-profile>
