version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - cd backend/apps/lambdas
      - npm install

  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - npm run lint || echo "No lint script found, skipping..."
      - npm run test || echo "No test script found, skipping..."

  build:
    commands:
      - echo "Building TypeScript Lambda functions..."
      - npm run build

      - echo "Creating deployment packages..."
      - mkdir -p dist/packages

      # Package each Lambda function separately
      - echo "Packaging preAuthentication..."
      - cd dist
      - zip -r packages/preAuthentication.zip pre-authentication.js shared.js node_modules/

      - echo "Packaging preTokenGeneration..."
      - zip -r packages/preTokenGeneration.zip pre-token-generation.js shared.js node_modules/

      - echo "Packaging defineAuthChallenge..."
      - zip -r packages/defineAuthChallenge.zip define-auth-challenge.js node_modules/

      - echo "Packaging createAuthChallenge..."
      - zip -r packages/createAuthChallenge.zip create-auth-challenge.js shared.js node_modules/

      - echo "Packaging verifyAuthChallenge..."
      - zip -r packages/verifyAuthChallenge.zip verify-auth-challenge.js shared.js node_modules/

      - cd ..

  post_build:
    commands:
      - echo "Uploading Lambda packages to S3..."

      - aws s3 cp dist/packages/preAuthentication.zip s3://$LAMBDA_BUCKET/lambdas/preAuthentication.zip
      - aws s3 cp dist/packages/preTokenGeneration.zip s3://$LAMBDA_BUCKET/lambdas/preTokenGeneration.zip
      - aws s3 cp dist/packages/defineAuthChallenge.zip s3://$LAMBDA_BUCKET/lambdas/defineAuthChallenge.zip
      - aws s3 cp dist/packages/createAuthChallenge.zip s3://$LAMBDA_BUCKET/lambdas/createAuthChallenge.zip
      - aws s3 cp dist/packages/verifyAuthChallenge.zip s3://$LAMBDA_BUCKET/lambdas/verifyAuthChallenge.zip

      - echo "Build completed successfully!"
      - echo "Uploaded Lambda packages:"
      - aws s3 ls s3://$LAMBDA_BUCKET/lambdas/ --human-readable

artifacts:
  files:
    - '**/*'
  base-directory: backend/apps/lambdas/dist/packages
  discard-paths: no

cache:
  paths:
    - 'backend/apps/lambdas/node_modules/**/*'
