apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
  namespace: default
data:
  region: "us-east-1"
  cognito-region: "us-east-1"
  s3-region: "us-east-1"
  ses-region: "us-east-1"
  sns-region: "us-east-1"
  sqs-region: "us-east-1"
