AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Master stack for Card Collector Backend CI/CD pipeline.
  Deploys Shared Services (artifact bucket) and Development (CodePipeline + CodeBuild) nested stacks.

Parameters:
  SharedAccountId:
    Type: String
    Description: AWS Account ID for Shared Services (artifact bucket).

  DevAccountId:
    Type: String
    Description: AWS Account ID for Development (pipeline + builds).

  Region:
    Type: String
    Default: us-east-1
    Description: Region for both Shared and Development stacks.

  RepoOwner:
    Type: String
    Default: lija12-3
    Description: GitHub repository owner.

  RepoName:
    Type: String
    Default: collectorcard
    Description: GitHub repository name.

  GitHubConnectionArn:
    Type: String
    Description: ARN of AWS CodeStar Connections GitHub connection.

  MainBranch:
    Type: String
    Default: main
  DevelopBranch:
    Type: String
    Default: develop
  FeatureBranch:
    Type: String
    Default: feat/CDEV-134_codepipeline

  TemplateBucketName:
    Type: String
    Description: S3 bucket where child templates (shared + backend) are stored.

Resources:
  SharedArtifactsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${Region}.amazonaws.com/shared-artifacts-stack.yaml"
      Parameters:
        SharedAccountId: !Ref SharedAccountId
        DevAccountId: !Ref DevAccountId
        Region: !Ref Region

  BackendPipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${Region}.amazonaws.com/backend-pipeline-stack.yaml"
      Parameters:
        DevAccountId: !Ref DevAccountId
        RepoOwner: !Ref RepoOwner
        RepoName: !Ref RepoName
        GitHubConnectionArn: !Ref GitHubConnectionArn
        MainBranch: !Ref MainBranch
        DevelopBranch: !Ref DevelopBranch
        FeatureBranch: !Ref FeatureBranch
        SharedArtifactBucket: !GetAtt SharedArtifactsStack.Outputs.ArtifactBucketName

Outputs:
  SharedArtifactBucketName:
    Description: Shared S3 artifact bucket name.
    Value: !GetAtt SharedArtifactsStack.Outputs.ArtifactBucketName

  BackendPipelineName:
    Description: Name of backend CodePipeline.
    Value: !GetAtt BackendPipelineStack.Outputs.BackendPipelineName

  DependencyCheckRuleName:
    Description: Weekly EventBridge rule name (for dependency audits).
    Value: !GetAtt BackendPipelineStack.Outputs.DependencyCheckRuleName
