AWSTemplateFormatVersion: '2010-09-09'
Description: Shared Services stack for the Card Collectors project - creates S3 artifact bucket with cross-account access.

Parameters:
  DevAccountId:
    Type: String
    Description: AWS Account ID of the Development account

Resources:
  # --------------------------------------------------
  # S3 Artifact Bucket
  # --------------------------------------------------
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub collectorcard-artifacts-shared-${AWS::AccountId}-${AWS::Region}-${AWS::StackName}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${DevAccountId}:root
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:GetBucketLocation
            Resource:
              - !Sub arn:aws:s3:::collectorcard-artifacts-shared-${AWS::AccountId}-${AWS::Region}-${AWS::StackName}
              - !Sub arn:aws:s3:::collectorcard-artifacts-shared-${AWS::AccountId}-${AWS::Region}-${AWS::StackName}/*
