AWSTemplateFormatVersion: '2010-09-09'
Description: Shared Services stack for Card Collectors project - creates S3 artifact bucket and ECR repo with cross-account access

Parameters:
  DevAccountId:
    Type: String
    Description: AWS Account ID of the Development account 

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub card-collector-artifacts-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Cross-account access to Development account
  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${DevAccountId}:root
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:GetBucketLocation
            Resource:
              - !Sub arn:aws:s3:::card-collector-artifacts-${AWS::AccountId}
              - !Sub arn:aws:s3:::card-collector-artifacts-${AWS::AccountId}/*

  BackendECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: backend
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images after 30 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": { "type": "expire" }
              }
            ]
          }

  ECRRepositoryPolicy:
    Type: AWS::ECR::RepositoryPolicy
    Properties:
      RepositoryName: !Ref BackendECR
      PolicyText:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${DevAccountId}:root
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload

Outputs:
  ArtifactBucketName:
    Value: !Ref ArtifactBucket
    Export:
      Name: SharedArtifactBucket
  ECRRepositoryUri:
    Value: !GetAtt BackendECR.RepositoryUri
    Export:
      Name: SharedECRRepositoryUri
